version: "2"

checks:
  argument-count:
    config:
      threshold: 10
  method-complexity:
    config:
      threshold: 20
  similar-code:
    enabled: false
  identical-code:
    enabled: false

plugins:
  fixme:
    enabled: true
  hlint:
    enabled: true
  markdownlint:
    enabled: true
